### ISSUE TITLE
Program crashing 

### ISSUE THREAD

**Issue by icdmkg2** [TerrificTable/Roblox-Account-Gen#4]
Hi the program crashed and spit out this error

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Desktop\Roblox-Account-Gen-v.1.1\main.py", line 56, in gen
    login(str(username), str(password), int(timeout), bool(False))
  File "C:\Users\User\Desktop\Roblox-Account-Gen-v.1.1\util\loginModule.py", line 31, in login
    day = Select(bot.find_element_by_xpath('//*[@id="DayDropdown"]'))
AttributeError: 'WebDriver' object has no attribute 'find_element_by_xpath'

**Comment by TerrificTable** [comment]
### I wrote this programm almost a year ago, it could be that chromedriver no longer supports `find_element_by_xpath`, It was about to be deprecated when I wrote this script/programm


#### If you want you can replace that with whatever its been replaced by (chromedriver refrences: https://chromedriver.chromium.org/getting-started, https://www.geeksforgeeks.org/find_element_by_xpath-driver-method-selenium-python)
#### I probably will not update this repository tho
